.TH feeder-server 1 2017\-02\-07
.SH NAME
feeder-server \- 
Run a webserver which serves cached RSS feeds over a REST
API. Command line options override defined values in config file, if
present.

.SH SYNOPSIS
 \fBfeeder server\fR [-h] [--debug] [--host HOST] [--port PORT] [-c CONFIG]


.SH DESCRIPTION

.br
Run a webserver which serves cached RSS feeds over a REST
.br
API. Command line options override defined values in config file, if
.br
present.
.br

.SH OPTIONS
  -h, --help            show this help message and exit
  --debug               run in debug mode
  --host HOST           host address to bind to
  --port PORT           port to bind to
  -c CONFIG, --config CONFIG
                        path to config file
.SH SEE ALSO
\fBfeeder\fR(1) \fBfeeder\-sync\fR(1) \fBfeeder\-pwhash\fR(1) \fBfeeder\-user\fR(1)
.SH AUTHORS
 Jonas Kalderstam <jonas@cowboyprogrammer.org>
.SH DISTRIBUTION
 The latest version of feeder server may be downloaded from https://github.com/spacecowboy/feeder