.TH feeder-sync 1 2017\-02\-07
.SH NAME
feeder-sync \- 
Synchronizes all known RSS feeds. This should probably be
run as a cronjob. See the bundled feeder-sync.timer.

.SH SYNOPSIS
 \fBfeeder sync\fR [-h] [-c CONFIG]


.SH DESCRIPTION

.br
Synchronizes all known RSS feeds. This should probably be
.br
run as a cronjob. See the bundled feeder\-sync.timer.
.br

.SH OPTIONS
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        path to config file
.SH SEE ALSO
\fBfeeder\fR(1) \fBfeeder\-server\fR(1) \fBfeeder\-pwhash\fR(1) \fBfeeder\-user\fR(1)
.SH AUTHORS
 Jonas Kalderstam <jonas@cowboyprogrammer.org>
.SH DISTRIBUTION
 The latest version of feeder sync may be downloaded from https://github.com/spacecowboy/feeder