.TH feeder-pwhash 1 2017\-02\-07
.SH NAME
feeder-pwhash \- 
Prints the hashed version of the passwords given, one per line.
Note that whitespace is stripped.

.SH SYNOPSIS
 \fBfeeder pwhash\fR [-h] password [password ...]


.SH DESCRIPTION

.br
Prints the hashed version of the passwords given, one per line.
.br
Note that whitespace is stripped.
.br

.SH OPTIONS
  password    passwords to hash

  -h, --help  show this help message and exit
.SH SEE ALSO
\fBfeeder\fR(1) \fBfeeder\-sync\fR(1) \fBfeeder\-server\fR(1) \fBfeeder\-user\fR(1)
.SH AUTHORS
 Jonas Kalderstam <jonas@cowboyprogrammer.org>
.SH DISTRIBUTION
 The latest version of feeder pwhash may be downloaded from https://github.com/spacecowboy/feeder