.TH feeder 1 2017\-02\-07
.SH NAME
feeder \- 
Cache RSS feeds and serve them with a REST API.

.SH SYNOPSIS
 \fBfeeder\fR [-h] [--version] {sync,server,pwhash,user} ...


.SH DESCRIPTION

.br
Cache RSS feeds and serve them with a REST API.
.br

.SH OPTIONS
  \fB-h\fR, \fB--help\fR
                        show this help message and exit
  \fB--version\fR       show program's version number and exit

  {sync,server,pwhash,user}
    sync                synchronize stored RSS feeds
    server              serve the REST API
    pwhash              hash a password
    user                add/set/remove users to the database
.SH SEE ALSO
\fBfeeder\-sync\fR(1) \fBfeeder\-server\fR(1) \fBfeeder\-pwhash\fR(1) \fBfeeder\-user\fR(1)
.SH AUTHORS
 Jonas Kalderstam <jonas@cowboyprogrammer.org>
.SH DISTRIBUTION
 The latest version of feeder may be downloaded from https://github.com/spacecowboy/feeder