#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  # Create user if it doesn't exist.
  if ! id feeder > /dev/null 2>&1 ; then
    adduser --system --home /var/lib/feeder --no-create-home \
            --ingroup nogroup --disabled-password --shell /bin/bash \
            feeder
  fi

  # directories needed
  mkdir -p /var/lib/feeder
  chown -R feeder /var/lib/feeder /etc/feeder
  chmod u+rwx /var/lib/feeder /etc/feeder
fi

#DEBHELPER#
