#!/bin/bash
set -euo pipefail

mkdir -p ${ANDROID_HOME}

if ! [ -d "${ANDROID_HOME}/tools" ]; then
  wget --quiet -O ${ANDROID_HOME}/tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  unzip -qq ${ANDROID_HOME}/tools.zip -d ${ANDROID_HOME}
fi
rm -f ${ANDROID_HOME}/tools.zip

echo y | sdkmanager --update
echo y | sdkmanager "tools" "platform-tools"
echo y | sdkmanager "extras;android;m2repository" "extras;google;google_play_services" "extras;google;m2repository"
echo y | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
echo y | sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
