#!/bin/bash

# Delete unsupported google play store languages
rm -rf fastlane/metadata/android/bs-BA \
   fastlane/metadata/android/eo \
   fastlane/metadata/android/tok \
   app/src/main/res/values-tok \
   fastlane/metadata/android/gl \
   app/src/main/res/values-gl \
   fastlane/metadata/android/eu \
   app/src/main/res/values-eu
