package com.nononsenseapps.feeder.db

const val FEEDS_TABLE_NAME = "feeds"
const val FEED_ITEMS_TABLE_NAME = "feed_items"

const val COL_ID = "id"
const val COL_TITLE = "title"
const val COL_CUSTOM_TITLE = "custom_title"
const val COL_URL = "url"
const val COL_TAG = "tag"
const val COL_NOTIFY = "notify"
const val COL_GUID = "guid"
const val COL_DESCRIPTION = "description"
const val COL_PLAINTITLE = "plain_title"
const val COL_PLAINSNIPPET = "plain_snippet"
const val COL_IMAGEURL = "image_url"
const val COL_ENCLOSURELINK = "enclosure_link"
const val COL_LINK = "link"
const val COL_AUTHOR = "author"
const val COL_PUBDATE = "pub_date"
const val COL_UNREAD = "unread"
const val COL_NOTIFIED = "notified"
const val COL_FEEDID = "feed_id"
const val COL_FEEDTITLE = "feed_title"
const val COL_FEEDURL = "feed_url"
