name: Health Test

on:
  push:
    branches:
      - healthcheck
  pull_request:

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Healthcheck start
        env:
          HC_PING_URL: ${{ secrets.HC_PING_URL }}
        run: curl -X GET "$HC_PING_URL/start"

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Healthcheck end
        env:
          HC_PING_URL: ${{ secrets.HC_PING_URL }}
        run: curl -X GET "$HC_PING_URL"
